#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "usage: ./input2params <input file>"
    exit 0
fi

echo backup existing params.txt...
cp params.txt params.txt.`date +%d_%m_%y.%H_%M`

echo generating new params.txt from $1...

cat $1 | awk '{if (NR>1) print NR-2, $1}' > params.txt

