#!/bin/csh

if ($#argv != 2) then
    echo "usage: ./params2input <params file> <input file>"
    exit 0
endif

echo generating new $2 from $1...

wc -l $1 | awk '{print $1-1}' > $2
cat $1 | awk '{print $2}' >> $2
